### ISSUE TITLE
libgfortran not loaded error when trying to dlopen generated library on macOS.

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/BinaryBuilder.jl#139]
Using https://github.com/KristofferC/OpenspecfunBuilder and replacing the `dlopen_e` with `dlopen` to see what the error is, I get:

```
julia> Pkg.build("SpecialFunctions")
INFO: Building SpecialFunctions
INFO: Found a valid dl path libopenspecfun.1.3.dylib while looking for libopenspecfun
INFO: /Users/kristoffer/.julia/v0.6/SpecialFunctions/deps/usr/lib/libopenspecfun.1.3.dylib matches our search criteria of libopenspecfun
========================================================================================================[ ERROR: SpecialFunctions ]========================================================================================================

LoadError: could not load library "/Users/kristoffer/.julia/v0.6/SpecialFunctions/deps/usr/lib/libopenspecfun.1.3.dylib"
dlopen(/Users/kristoffer/.julia/v0.6/SpecialFunctions/deps/usr/lib/libopenspecfun.1.3.dylib, 1): Library not loaded: /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/lib/libgfortran.4.dylib
  Referenced from: /Users/kristoffer/.julia/v0.6/SpecialFunctions/deps/usr/lib/libopenspecfun.1.3.dylib
  Reason: image not found
while loading /Users/kristoffer/.julia/v0.6/SpecialFunctions/deps/build.jl, in expression starting on line 24
```

on macOS.

**Comment by staticfloat** [comment]
This is a great fortran test; In your Julia, what `libgfortran` is already loaded?

**Comment by KristofferC** [comment]
```
julia> Libdl.dllist()[contains.(Libdl.dllist(), "libgfortran")]
1-element Array{AbstractString,1}:
 "/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/libgfortran.4.dylib"
```

**Comment by staticfloat** [comment]
Okay, so we are failing to rewrite the dependency to an `@rpath` one.

**Comment by KristofferC** [comment]
In the logs I also see:

```
INFO: Beginning audit of /home/travis/build/KristofferC/OpenspecfunBuilder/build/i686-linux-gnu/gkbwBvwh/destdir
INFO: Checking lib/libopenspecfun.so with RPath list Any[]
WARNING: Linked library libquadmath.so.0 could not be resolved and could not be auto-mapped
INFO: Checking lib/libopenspecfun.so.1 with RPath list Any[]
WARNING: Linked library libquadmath.so.0 could not be resolved and could not be auto-mapped
INFO: Checking lib/libopenspecfun.so.1.3 with RPath list Any[]
WARNING: Linked library libquadmath.so.0 could not be resolved and could not be auto-mapped
```

which is a dependency `gfortran` always put there, I think.

**Comment by staticfloat** [comment]
This should be fixed now.

**Comment by KristofferC** [comment]
Doesn't seem fixed: https://github.com/JuliaMath/OpenspecfunBuilder/issues/9

```
dlopen(deps/usr/lib/libopenspecfun.1.3.dylib, 1): Library not loaded: @rpath/libgfortran.4.dylib
  Referenced from: /Users/kristoffer/.julia/v0.6/SpecialFunctions/deps/usr/lib/libopenspecfun.1.3.dylib
```

```
julia> Libdl.dllist()[contains.(Libdl.dllist(), "libgfortran")]
 "/usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib"
```

**Comment by KristofferC** [comment]
Or, well, it seems to be an `@rpath` now but it still fails to load.

**Comment by KristofferC** [comment]
Ok, dup of https://github.com/JuliaLinearAlgebra/OpenBLASBuilder/issues/2
